server:
  port: 8086

spring:
  application:
    name: service-driver-user
  datasource:
    url: jdbc:mysql://localhost:3306/service-driver-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848