server:
  port: 8085

spring:
  application:
    name: service-map
  datasource:
    url: jdbc:mysql://localhost:3306/service-map?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

amap:
  key: ba81aa920fc583b0c5e5180c82bba1bc